In [1]:
import pandas as pd
import numpy as np

In [2]:
sentences = [
    "The sun rises in the east",
    "She loves reading books",
    "He plays football every weekend",
    "The cat is sleeping on the couch",
    "I am learning to cook delicious meals",
    "They are planning a trip to the mountains",
    "My best friend lives in New York",
    "The weather is very cold today",
    "We enjoyed watching the fireworks last night",
    "Her garden is full of beautiful flowers"
]


In [3]:
label = [10, 0, 1, 1, 1, 0, 0, 1, 0, 0]

In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [5]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [6]:
tokens = Tokenizer(oov_token = 'oov')
tokens.fit_on_texts(sentences)

In [7]:
vocab = tokens.word_index

In [8]:
vocab

{'oov': 1,
 'the': 2,
 'is': 3,
 'in': 4,
 'to': 5,
 'sun': 6,
 'rises': 7,
 'east': 8,
 'she': 9,
 'loves': 10,
 'reading': 11,
 'books': 12,
 'he': 13,
 'plays': 14,
 'football': 15,
 'every': 16,
 'weekend': 17,
 'cat': 18,
 'sleeping': 19,
 'on': 20,
 'couch': 21,
 'i': 22,
 'am': 23,
 'learning': 24,
 'cook': 25,
 'delicious': 26,
 'meals': 27,
 'they': 28,
 'are': 29,
 'planning': 30,
 'a': 31,
 'trip': 32,
 'mountains': 33,
 'my': 34,
 'best': 35,
 'friend': 36,
 'lives': 37,
 'new': 38,
 'york': 39,
 'weather': 40,
 'very': 41,
 'cold': 42,
 'today': 43,
 'we': 44,
 'enjoyed': 45,
 'watching': 46,
 'fireworks': 47,
 'last': 48,
 'night': 49,
 'her': 50,
 'garden': 51,
 'full': 52,
 'of': 53,
 'beautiful': 54,
 'flowers': 55}

In [9]:
sequence = tokens.texts_to_sequences(sentences)

In [10]:
sequence

[[2, 6, 7, 4, 2, 8],
 [9, 10, 11, 12],
 [13, 14, 15, 16, 17],
 [2, 18, 3, 19, 20, 2, 21],
 [22, 23, 24, 5, 25, 26, 27],
 [28, 29, 30, 31, 32, 5, 2, 33],
 [34, 35, 36, 37, 4, 38, 39],
 [2, 40, 3, 41, 42, 43],
 [44, 45, 46, 2, 47, 48, 49],
 [50, 51, 3, 52, 53, 54, 55]]

In [11]:
sequences = pad_sequences(sequence, maxlen=6, padding = 'post', truncating='post')

In [12]:
sequences

array([[ 2,  6,  7,  4,  2,  8],
       [ 9, 10, 11, 12,  0,  0],
       [13, 14, 15, 16, 17,  0],
       [ 2, 18,  3, 19, 20,  2],
       [22, 23, 24,  5, 25, 26],
       [28, 29, 30, 31, 32,  5],
       [34, 35, 36, 37,  4, 38],
       [ 2, 40,  3, 41, 42, 43],
       [44, 45, 46,  2, 47, 48],
       [50, 51,  3, 52, 53, 54]], dtype=int32)

In [13]:
sequences.shape

(10, 6)

In [14]:
 sequences.shape[0]

10

In [15]:
label = np.array(label).reshape(-1)

In [16]:
from keras.models import Sequential
from keras.layers import SimpleRNN,Dense

In [17]:
model = Sequential()

In [18]:
model.add(SimpleRNN(1, input_shape=(sequences.shape[1],1), activation = 'relu' ))
model.add(Dense(1, activation = 'sigmoid'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [19]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [20]:
model.fit(sequences, label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.4000 - loss: 122.3948


In [21]:
test = ['I found a gem yesterday']

In [22]:
test = tokens.texts_to_sequences(test)

In [23]:
test = pad_sequences(test, padding = 'post', truncating = 'post', maxlen = 6)

In [24]:
test

array([[22,  1, 31,  1,  1,  0]], dtype=int32)

In [25]:
test.shape

(1, 6)

In [26]:
model.predict(test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step


array([[1.]], dtype=float32)

In [27]:
tokens.word_index

{'oov': 1,
 'the': 2,
 'is': 3,
 'in': 4,
 'to': 5,
 'sun': 6,
 'rises': 7,
 'east': 8,
 'she': 9,
 'loves': 10,
 'reading': 11,
 'books': 12,
 'he': 13,
 'plays': 14,
 'football': 15,
 'every': 16,
 'weekend': 17,
 'cat': 18,
 'sleeping': 19,
 'on': 20,
 'couch': 21,
 'i': 22,
 'am': 23,
 'learning': 24,
 'cook': 25,
 'delicious': 26,
 'meals': 27,
 'they': 28,
 'are': 29,
 'planning': 30,
 'a': 31,
 'trip': 32,
 'mountains': 33,
 'my': 34,
 'best': 35,
 'friend': 36,
 'lives': 37,
 'new': 38,
 'york': 39,
 'weather': 40,
 'very': 41,
 'cold': 42,
 'today': 43,
 'we': 44,
 'enjoyed': 45,
 'watching': 46,
 'fireworks': 47,
 'last': 48,
 'night': 49,
 'her': 50,
 'garden': 51,
 'full': 52,
 'of': 53,
 'beautiful': 54,
 'flowers': 55}